
[theme]
name = "gruvbox-dark"

# [theme.overrides]
# idle_bg = "#ff000000"
# idle_fg = "#ffffff"

[icons]
name = "awesome"

[icons.overrides]
time = " "
# bat_full = ""
# bat_charging = " ^"
# bat_discharging = " ~"
# net_wireless = ""
# net_wired = " eth"

[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "memory"
icons = false
clickable = false
format_mem = "{Mug} GiB"
interval = 1

[[block]]
block = "net"
device = "wlp59s0"
ssid = true
speed_up = false
speed_down = false
interval = 1

[[block]]
block = "net"
device = "enxe4b97addfedc"
ip = true
ssid = false
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "battery"
format = "{percentage}%"

[[block]]
block = "sound"

[[block]]
block = "time"
format = "%Y-%m-%d"
interval = 60

[[block]]
block = "time"
format = "%H:%M"
interval = 1
